const mineflayer = require('mineflayer');
const bot = mineflayer.createBot({ host: '127.0.0.1', port: 25565, username: 'HomeProbe', auth: 'offline' });
const msgs = [];
let done = false;
const finish = (c) => { if (done) return; done = true; try { bot.quit(); } catch (e) {} setTimeout(() => process.exit(c), 400); };
bot.on('message', (m) => { const s = m.toString().trim(); if (s) msgs.push(s); });
const run = (cmd, wait) => new Promise(r => { console.log('>> ' + cmd); bot.chat(cmd); setTimeout(r, wait); });
bot.once('spawn', async () => {
  const p0 = bot.entity.position.clone();
  console.log('SPAWNED at ' + [p0.x.toFixed(1), p0.y.toFixed(1), p0.z.toFixed(1)].join(','));
  await new Promise(r => setTimeout(r, 4000));
  msgs.length = 0;
  await run('/homes', 2500);
  await run('/setspawn', 2500);
  await run('/spawn', 3500);
  const p1 = bot.entity.position;
  await run('/sethome second', 2500);
  await run('/homes', 2500);
  console.log('--- RESPONSES ---');
  for (const m of msgs.slice(0, 22)) console.log('  ' + m);
  console.log('position after /spawn: ' + [p1.x.toFixed(1), p1.y.toFixed(1), p1.z.toFixed(1)].join(','));
  finish(0);
});
bot.on('error', (e) => { console.log('ERROR: ' + e.message); finish(1); });
bot.on('kicked', (r) => { console.log('KICKED'); finish(1); });
setTimeout(() => { console.log('TIMEOUT'); for (const m of msgs.slice(0,22)) console.log('  ' + m); finish(1); }, 70000);
