const mineflayer = require('mineflayer');
const bot = mineflayer.createBot({ host: '127.0.0.1', port: 25565, username: 'TeamProbe3', auth: 'offline' });
let done = false;
const finish = (c) => { if (done) return; done = true; try { bot.quit(); } catch (e) {} setTimeout(() => process.exit(c), 400); };
bot._client.on('teams', (p) => {
  console.log('--- SetPlayerTeam ---');
  console.log('  team            : ' + p.team);
  console.log('  mode            : ' + p.mode);
  console.log('  displayName     : ' + JSON.stringify(p.name));
  console.log('  prefix          : ' + JSON.stringify(p.prefix));
  console.log('  suffix          : ' + JSON.stringify(p.suffix));
  console.log('  formatting      : ' + p.formatting);
  console.log('  nameTagVisibility: ' + p.nameTagVisibility);
  console.log('  collisionRule   : ' + p.collisionRule);
  console.log('  flags           : ' + p.flags);
  console.log('  players         : ' + JSON.stringify(p.players));
});
bot.once('spawn', () => { console.log('SPAWNED v' + bot.version); setTimeout(() => finish(0), 8000); });
bot.on('error', (e) => { console.log('ERROR: ' + e.message); finish(1); });
setTimeout(() => finish(1), 60000);
