/// Add one definition here to offer another bundled addon in both frontends.
/// Workspace-local additions use the same schema in .multiplexor/addons.json.
const List<String> _bukkitServers = <String>[
  'paper',
  'purpur',
  'leaf',
  'spigot',
];
const List<String> _viaServers = <String>[..._bukkitServers, 'folia', 'canvas'];

const List<Map<String, Object?>> builtinAddons = <Map<String, Object?>>[
  <String, Object?>{
    'id': 'essentialsx',
    'name': 'EssentialsX',
    'kind': 'plugin',
    'description': 'Core commands, homes, warps and economy.',
    'serverTypes': _bukkitServers,
    'filePrefixes': <String>[
      'essentialsx-',
      'essentialsx.jar',
      'essentials.jar',
    ],
    'source': <String, Object?>{'type': 'modrinth', 'project': 'hXiIvTyT'},
  },
  <String, Object?>{
    'id': 'fawe',
    'name': 'FastAsyncWorldEdit (FAWE)',
    'kind': 'plugin',
    'description': 'Fast WorldEdit building and editing tools.',
    'serverTypes': _bukkitServers,
    'filePrefixes': <String>['fastasyncworldedit', 'worldedit'],
    'source': <String, Object?>{'type': 'modrinth', 'project': 'z4HZZnLr'},
  },
  <String, Object?>{
    'id': 'viaversion',
    'name': 'ViaVersion',
    'kind': 'plugin',
    'description': 'Allow newer Minecraft clients to join.',
    'serverTypes': _viaServers,
    'filePrefixes': <String>['viaversion'],
    'source': <String, Object?>{
      'type': 'modrinth',
      'project': 'P1OZGk5p',
      'loaders': <String>['paper'],
    },
  },
  <String, Object?>{
    'id': 'viabackwards',
    'name': 'ViaBackwards',
    'kind': 'plugin',
    'description': 'Allow older clients to join; includes ViaVersion.',
    'serverTypes': _viaServers,
    'dependencies': <String>['viaversion'],
    'filePrefixes': <String>['viabackwards'],
    'source': <String, Object?>{
      'type': 'modrinth',
      'project': 'NpvuJQoq',
      'loaders': <String>['paper'],
    },
  },
  <String, Object?>{
    'id': 'protocollib',
    'name': 'ProtocolLib',
    'kind': 'plugin',
    'description':
        'Packet API for plugins. Newer MC versions use the official development build.',
    'serverTypes': _viaServers,
    'filePrefixes': <String>['protocollib'],
    'sources': <Map<String, Object?>>[
      <String, Object?>{
        'type': 'github',
        'repo': 'dmulloy2/ProtocolLib',
        'tag': '5.4.0',
        'asset': 'ProtocolLib.jar',
        'minecraftVersions': <String>[
          '1.8',
          '1.8.1',
          '1.8.2',
          '1.8.3',
          '1.8.4',
          '1.8.5',
          '1.8.6',
          '1.8.7',
          '1.8.8',
          '1.8.9',
          '1.9',
          '1.9.1',
          '1.9.2',
          '1.9.3',
          '1.9.4',
          '1.10',
          '1.10.1',
          '1.10.2',
          '1.11',
          '1.11.1',
          '1.11.2',
          '1.12',
          '1.12.1',
          '1.12.2',
          '1.13',
          '1.13.1',
          '1.13.2',
          '1.14',
          '1.14.1',
          '1.14.2',
          '1.14.3',
          '1.14.4',
          '1.15',
          '1.15.1',
          '1.15.2',
          '1.16',
          '1.16.1',
          '1.16.2',
          '1.16.3',
          '1.16.4',
          '1.16.5',
          '1.17',
          '1.17.1',
          '1.18',
          '1.18.1',
          '1.18.2',
          '1.19',
          '1.19.1',
          '1.19.2',
          '1.19.3',
          '1.19.4',
          '1.20',
          '1.20.1',
          '1.20.2',
          '1.20.3',
          '1.20.4',
          '1.20.5',
          '1.20.6',
          '1.21',
          '1.21.1',
          '1.21.2',
          '1.21.3',
          '1.21.4',
          '1.21.5',
          '1.21.6',
          '1.21.7',
          '1.21.8',
        ],
      },
      <String, Object?>{
        'type': 'github',
        'repo': 'dmulloy2/ProtocolLib',
        'tag': 'dev-build',
        'asset': 'ProtocolLib-Spigot.jar',
        'label': 'development',
        'minecraftVersions': <String>[
          '1.21.9',
          '1.21.10',
          '1.21.11',
          '26.1',
          '26.1.1',
          '26.1.2',
        ],
      },
      <String, Object?>{
        'type': 'github',
        'repo': 'dmulloy2/ProtocolLib',
        'tag': 'dev-build',
        'asset': 'ProtocolLib.jar',
        'label': 'development',
        'serverTypes': <String>['paper', 'purpur', 'canvas', 'leaf', 'folia'],
        'minecraftVersions': <String>['26.2'],
      },
      <String, Object?>{
        'type': 'github',
        'repo': 'dmulloy2/ProtocolLib',
        'tag': 'dev-build',
        'asset': 'ProtocolLib-Spigot.jar',
        'label': 'development',
        'serverTypes': <String>['spigot'],
        'minecraftVersions': <String>['26.2'],
      },
    ],
  },
];
